# LiveLab: Creating a Simple Dash App 


## Dataset Description:

You are working with a college sports dataset from [Kaggle](https://www.kaggle.com/datasets/umerhaddii/us-collegiate-sports-dataset)

### Step 1:  Load & Inspect Data

In [1]:
#Import pandas, plotly, and dash packages 
import dash
from dash import html, dcc
from dash.dependencies import Input, Output
import pandas as pd
import plotly.express as px

In [3]:
# Read in the data 

df = pd.read_csv("/Users/beans/Desktop/Marcy_Lab/DA2025_Lectures/Mod2/data/sports.csv")
df.head()

/var/folders/3y/ldxff8k17wjcyzkq19xw1srm0000gn/T/ipykernel_45636/1593794274.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/beans/Desktop/Marcy_Lab/DA2025_Lectures/Mod2/data/sports.csv")

,year,unitid,institution_name,city_txt,state_cd,zip_text,classification_code,classification_name,classification_other,ef_male_count,...,partic_coed_women,sum_partic_men,sum_partic_women,rev_men,rev_women,total_rev_menwomen,exp_men,exp_women,total_exp_menwomen,sports
0,2015,100654,Alabama A & M University,Normal,AL,35762.0,2,NCAA Division I-FCS,NaN,1923,...,NaN,31,0,345592.0,NaN,345592.0,397818.0,NaN,397818.0,Baseball
1,2015,100654,Alabama A & M University,Normal,AL,35762.0,2,NCAA Division I-FCS,NaN,1923,...,NaN,19,16,1211095.0,748833.0,1959928.0,817868.0,742460.0,1560328.0,Basketball
2,2015,100654,Alabama A & M University,Normal,AL,35762.0,2,NCAA Division I-FCS,NaN,1923,...,NaN,61,46,183333.0,315574.0,498907.0,246949.0,251184.0,498133.0,All Track Combined
3,2015,100654,Alabama A & M University,Normal,AL,35762.0,2,NCAA Division I-FCS,NaN,1923,...,NaN,99,0,2808949.0,NaN,2808949.0,3059353.0,NaN,3059353.0,Football
4,2015,100654,Alabama A & M University,Normal,AL,35762.0,2,NCAA Division I-FCS,NaN,1923,...,NaN,9,0,78270.0,NaN,78270.0,83913.0,NaN,83913.0,Golf

### Step 2:  Clean the Data and Only keep the Revenue Columns

In [43]:
# Drop the NAs on the revenue columns 

df_clean = df[['rev_women','rev_men']].dropna()
df_clean.head()

    rev_women    rev_men
1    748833.0  1211095.0
2    315574.0   183333.0
7    131145.0    78274.0
11  1966556.0  4189826.0
13   346987.0   407728.0

### Step 3:  Compute Averages and Put in a New DataFrame

In [8]:
# Compute averages
avg_men = df_clean['rev_men'].mean()
avg_women = df_clean['rev_women'].mean()

# Put in a new DataFrame for plotting
df_plot = pd.DataFrame({
    "Gender": ["Men", "Women"],
    "Average Revenue": [avg_men, avg_women]
})

### Step 4:  Plot the Data

In [9]:
# Plot grouped bar chart of Gender and Average Revenue 
fig = px.bar(df_plot, x='Gender', y='Average Revenue', title="Average Sports Revenue by Gender")
fig.show()

### Step 4 Build the Dash App

In [11]:
app = dash.Dash(__name__)
app.title = "Sports Dash"

app.layout = html.Div([
    html.H1("Average Revenue by Gender", style={'textAlign': 'center'}),
    dcc.Graph(figure=fig)
])

if __name__ == "__main__":
    app.run(debug=True)

### Step 5:  View in Browser

Open up a browser to see if it pops up:  http://localhost:8050/